[package]
name = "moirai-async-macros"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"
homepage.workspace = true
documentation = "https://docs.rs/moirai-async-macros"
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true
description = "Proc-macros for moirai-async runtime"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"
